on:
  push:
    branches:
      - main
name: ğŸš€ Deploy to InfinityFree
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4

    - name: ğŸ” Create DB Credentials File
      run: |
        echo "<?php" > config/db_credentials.php
        echo "\$db_host = '${{ secrets.DB_HOST }}';" >> config/db_credentials.php
        echo "\$db_name = '${{ secrets.DB_NAME }}';" >> config/db_credentials.php
        echo "\$db_user = '${{ secrets.DB_USER }}';" >> config/db_credentials.php
        echo "\$db_pass = '${{ secrets.DB_PASS }}';" >> config/db_credentials.php
        echo "?>" >> config/db_credentials.php
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: htdocs/

